name: Autograder
run-name: ${{ github.actor }} is getting graded!
on: [push]
jobs:
  Autograder:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Java JDK to path
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Adding python to path
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Checking out repository code
        uses: actions/checkout@v4

      - name: Running autograder
        run: |
          python3 .github/workflows/autograder.py
      
